apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: cloudflare
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: cloudflare
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-services
  namespace: cloudflare
spec:
  podSelector:
    matchLabels:
      app: cloudflared
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: immich
    ports:
    - protocol: TCP
      port: 2283
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: jellyfin
    ports:
    - protocol: TCP
      port: 8096
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: argocd
    ports:
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: actual
    ports:
    - protocol: TCP
      port: 5006
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
