# Template for Cloudflare Tunnel credentials
# DO NOT commit the actual secret to Git
# This is a template showing the structure

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "YOUR_ACCOUNT_ID",
      "TunnelSecret": "YOUR_TUNNEL_SECRET",
      "TunnelID": "YOUR_TUNNEL_ID"
    }
  tunnel-token: "YOUR_TUNNEL_TOKEN"
